environment: 
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          DB: 10.4.18

        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          DB: 10.4.18

        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          DB: 10.5.9

# scripts that are called at very beginning, before repo cloning
init:
    - git config --global core.autocrlf input
    - wmic cpu get NumberOfCores
    - wmic ComputerSystem get TotalPhysicalMemory

clone_folder: c:\maodbc
platform: x64
configuration: Release

build_script:
    # build libmariadb separately first because otherwise the Wix installer build might look for files that aren't available yet
    - cd libmariadb
    - cmake --build . --config RelWithDebInfo --parallel 2
    # build conncpp
    - cd ..
    - cmake --build . --config RelWithDebInfo --parallel 2

# scripts to run before build
before_build:
    - cd c:\maodbc
    - git submodule init
    - git submodule update
    - rm -rf win64
    - mkdir win64
    - cd win64
    - cmake .. -DCONC_WITH_MSI=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_SIGNCODE=0 -DWITH_SSL=SCHANNEL 

install:
    # download and install MariaDB Server
    - cmd: appveyor-download.bat
    - msiexec /i server.msi INSTALLDIR=c:\mariadb-server SERVICENAME=mariadb /qn
    # create test database
    #- c:\mariadb-server\bin\mysql.exe -e "CREATE DATABASE test" --user=root
after_build:
    # install built driver
    - ps: $msifile = Get-ChildItem $env:APPVEYOR_BUILD_FOLDER\win64\wininstall\mariadb-connector-*.msi | Select-Object -First 1
    - ps: Push-AppveyorArtifact $msifile.FullName -FileName $msifile.Name
    - ps: Write $msifile
    - ps: msiexec /i $msifile INSTALLDIR=c:\mariadb-conncpp /qn 

    - timeout /T 1    
    # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    - cd test
    - ctest -V

on_finish:
#  - dir
#  - dir RelWithDebInfo
#  - dir wininstall
#  - dir libmariadb\RelWithDebInfo
#  - dir release
#  - dir libmariadb
#  - dir libmariadb\release
#  - dir wininstall
#  - type wininstall\mariadb_odbc.xml
